import type { Metadata } from "next";
import "./globals.css";
import Cookie from "@/components/Landing/Cookie/Cookie";
import Providers from "./Provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google Fonts link for Poppins */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@100;300;400;600;700&display=swap"
        />
        <script src="https://cryptorank.io/widget/marquee.js"></script>
      </head>
      <body className="text-[#ddd]">
        <Providers>
          <Cookie />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
