import type { Metadata } from "next";
import "./globals.css";
import Cookie from "@/components/Landing/Cookie/Cookie";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google Fonts link for Poppins */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@100;300;400;600;700&display=swap"
        />
      </head>
      <body className="text-[#ddd]">
        <Cookie />
        {children}
      </body>
    </html>
  );
}
